- name: Wait until SSH is available  
  local_action: 
    module: wait_for 
    host: "{{ public_ip_address }}"
    port: 22 
    delay: 10 
    timeout: 320 
    state: started
    
- name: Install pkutils
  sudo: yes
  pip: name=pkutils virtualenv={{ virtualenv_directory }}

- name: Install Ongair via PIP
  sudo: yes
  pip: name=ongair-whatsapp virtualenv={{ virtualenv_directory }} state=latest

- name: Create log Directory
  sudo: yes
  file: state=directory path={{project_directory}}logs owner={{deploy_user}} group={{deploy_user}}

- name: Create tmp Directory
  sudo: yes
  file: state=directory path={{project_directory}}tmp owner={{deploy_user}} group={{deploy_user}}

- name: Install cron monitoring task
  cron: name='Monitor ongair' minute='*/3' job="sudo {{ virtualenv_directory }}bin/ongair-monitor-cli >> {{ project_directory }}logs/monitoring.log"

- name: Install facts directory
  sudo: yes
  file: state=directory path="/etc/ansible/facts.d"

- name: Create facts file
  sudo: yes
  file: path="/etc/ansible/facts.d/agents.fact" owner={{ deploy_user }} group={{ deploy_user }} state=touch

- name: Copy Agent Scripts
  sudo: yes
  copy: src=set-agents.py 
        dest=/opt/set-agents.py 
        owner={{ deploy_user }} 
        group={{ deploy_user }} mode=755
  
- name: Writing facts
  command: /opt/set-agents.py