- name: Stop the service
  sudo: yes
  service: name=ongair-{{account_number}} state=stopped

- name: Remove axolotl db
  sudo: yes
  file: state=absent path=/root/.yowsup/{{account_number}}/axolotl.db

- name: Start the service
  sudo: yes
  service: name=ongair-{{account_number}} state=started